/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class CrearDialog extends javax.swing.JDialog {

    /**
     * Creates new form CrearDialog
     */
    public CrearDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bCrear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        etId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        etNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        etFecha = new javax.swing.JFormattedTextField();
        etNota = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear Matricula");
        setIconImage(null);

        bCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/agregar-usuario.png"))); // NOI18N
        bCrear.setText("Crear");
        bCrear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearActionPerformed(evt);
            }
        });

        jLabel1.setText("Id");

        etId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                etIdKeyTyped(evt);
            }
        });

        jLabel2.setText("Nombre");

        etNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                etNombreKeyTyped(evt);
            }
        });

        jLabel3.setText("Nota");

        jLabel4.setText("Fecha");

        etFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yy"))));
        etFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                etFechaKeyTyped(evt);
            }
        });

        etNota.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        etNota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                etNotaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etId)
                    .addComponent(etNombre)
                    .addComponent(etFecha)
                    .addComponent(etNota, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(bCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(etNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(etNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(etFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(bCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearActionPerformed
        if (etId.getText().isEmpty() || etNombre.getText().isEmpty() || etNota.getText().isEmpty() || etFecha.getText().isEmpty()) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "No puede haber un campo vacío", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (Double.parseDouble(etNota.getText().replace(",", "."))>10||Double.parseDouble(etNota.getText().replace(",", "."))<0) {
                getToolkit().beep();
                JOptionPane.showMessageDialog(this, "La nota tiene que estar comprendida entre 0 y 10", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
                try {
                    File f = new File(VistaMain.path);
                    RandomAccessFile randomAccessFile = new RandomAccessFile(f, "rw");
                    int id = Integer.parseInt(etId.getText());
                    randomAccessFile.seek((id - 1) * VistaMain.TAMANIO);
                    if (((id - 1) * VistaMain.TAMANIO) >= randomAccessFile.length()) {
                        randomAccessFile.seek((id - 1) * VistaMain.TAMANIO);
                        randomAccessFile.writeInt(id);
                        StringBuffer sb = new StringBuffer(etNombre.getText());
                        sb.setLength(20);
                        randomAccessFile.writeChars(sb.toString());
                        Double nota = Double.parseDouble(etNota.getText().replace(",", "."));
                        randomAccessFile.writeDouble(nota);
                        StringBuffer sbfecha = new StringBuffer(etFecha.getText());
                        sbfecha.setLength(8);
                        randomAccessFile.writeChars(sbfecha.toString());
                        getToolkit().beep();
                        JOptionPane.showMessageDialog(this, "La matricula de id " + id + " ha sido añadida correctamente");
                    } else {
                        int aux = randomAccessFile.readInt();
                        if (aux == id) {
                            getToolkit().beep();
                            JOptionPane.showMessageDialog(this, "La matricula de id " + id + " ya existe", "Error", JOptionPane.ERROR_MESSAGE);
                        } else {
                            randomAccessFile.seek((id - 1) * VistaMain.TAMANIO);
                            randomAccessFile.writeInt(id);
                            StringBuffer sb = new StringBuffer(etNombre.getText());
                            sb.setLength(20);
                            randomAccessFile.writeChars(sb.toString());
                            Double nota = Double.parseDouble(etNota.getText().replace(",", "."));
                            randomAccessFile.writeDouble(nota);
                            StringBuffer sbfecha = new StringBuffer(etFecha.getText());
                            sbfecha.setLength(8);
                            randomAccessFile.writeChars(sbfecha.toString());
                            getToolkit().beep();
                            JOptionPane.showMessageDialog(this, "La matricula de id " + id + " ha sido añadida correctamente");
                        }
                    }
                    randomAccessFile.close();
                } catch (IOException ex) {
                    System.out.println("Ha ocurrido un error: " + ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_bCrearActionPerformed

    private void etIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etIdKeyTyped
        char num = evt.getKeyChar();
        if (!Character.isDigit(num) && evt.getKeyChar() != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_etIdKeyTyped

    private void etFechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etFechaKeyTyped
        char dig = evt.getKeyChar();
        if (!Character.isDigit(dig) && evt.getKeyChar() != KeyEvent.VK_SLASH && evt.getKeyChar() != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "El formato de la fecha es: dd/mm/yy", "Error en el formato", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_etFechaKeyTyped

    private void etNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etNombreKeyTyped
        char letra = evt.getKeyChar();
        if (etNombre.getText().length() == 20) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "El nombre contiene un máximo de 20 letras", "Error en el tamaño", JOptionPane.ERROR_MESSAGE);
        } else {
            if (!Character.isAlphabetic(letra) && evt.getKeyChar() != KeyEvent.VK_SPACE && evt.getKeyChar() != KeyEvent.VK_BACK_SPACE && evt.getKeyChar() != KeyEvent.VK_SHIFT) {
                evt.consume();
                getToolkit().beep();
            }
        }
    }//GEN-LAST:event_etNombreKeyTyped

    private void etNotaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etNotaKeyTyped
        char num = evt.getKeyChar();
        if (!Character.isDigit(num) && evt.getKeyChar() != KeyEvent.VK_BACK_SPACE && evt.getKeyChar() != KeyEvent.VK_COMMA) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_etNotaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CrearDialog dialog = new CrearDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCrear;
    private javax.swing.JFormattedTextField etFecha;
    private javax.swing.JTextField etId;
    private javax.swing.JTextField etNombre;
    private javax.swing.JFormattedTextField etNota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
