/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.io.RandomAccessFile;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class ModificarDialog extends javax.swing.JDialog {

    /**
     * Creates new form ModificarDialog
     */
    public ModificarDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        etNombreModificar.setText(VistaMain.nomModif);
        etNotaModificar.setText(VistaMain.notModif.toString());
        etFechaModificar.setText(VistaMain.fecModif);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bModificar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        etNombreModificar = new javax.swing.JTextField();
        etNotaModificar = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        etFechaModificar = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/editar-usuario.png"))); // NOI18N
        bModificar.setText("Editar");
        bModificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre");

        etNombreModificar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                etNombreModificarKeyTyped(evt);
            }
        });

        etNotaModificar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        etNotaModificar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                etNotaModificarKeyTyped(evt);
            }
        });

        jLabel3.setText("Nota");

        jLabel4.setText("Fecha");

        etFechaModificar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yy"))));
        etFechaModificar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                etFechaModificarKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(42, 42, 42)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(etNombreModificar)
                                .addComponent(etFechaModificar)
                                .addComponent(etNotaModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(94, 94, 94)
                            .addComponent(bModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(91, 91, 91)))
                    .addContainerGap(62, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(etNombreModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(etNotaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(etFechaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addComponent(bModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(55, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        if (etNombreModificar.getText().isEmpty() || etNotaModificar.getText().isEmpty() || etFechaModificar.getText().isEmpty()) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "No puede haber un campo vacío", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (Double.parseDouble(etNotaModificar.getText().replace(",", ".")) > 10 || Double.parseDouble(etNotaModificar.getText().replace(",", ".")) < 0) {
                getToolkit().beep();
                JOptionPane.showMessageDialog(this, "La nota tiene que estar comprendida entre 0 y 10", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                try {
                    File f = new File(VistaMain.path);
                    RandomAccessFile randomAccessFile = new RandomAccessFile(f, "rw");
                    int id = VistaMain.idModif;
                    randomAccessFile.seek((id - 1) * VistaMain.TAMANIO);
                    randomAccessFile.writeInt(id);
                    StringBuffer sb = new StringBuffer(etNombreModificar.getText());
                    sb.setLength(20);
                    randomAccessFile.writeChars(sb.toString());
                    Double nota = Double.parseDouble(etNotaModificar.getText().replace(",", "."));
                    randomAccessFile.writeDouble(nota);
                    StringBuffer sbfecha = new StringBuffer(etFechaModificar.toString());
                    sbfecha.setLength(8);
                    randomAccessFile.writeChars(sbfecha.toString());
                    getToolkit().beep();
                    JOptionPane.showMessageDialog(this, "La matricula de id " + id + " ha sido modificada correctamente");
                    randomAccessFile.close();
                } catch (IOException ex) {
                    System.out.println("Ha ocurrido un error: " + ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_bModificarActionPerformed

    private void etNombreModificarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etNombreModificarKeyTyped
        char letra = evt.getKeyChar();
        if (etNombreModificar.getText().length() == 20) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "El nombre contiene un máximo de 20 letras", "Error en el tamaño", JOptionPane.ERROR_MESSAGE);
        } else {
            if (!Character.isAlphabetic(letra) && evt.getKeyChar() != KeyEvent.VK_SPACE && evt.getKeyChar() != KeyEvent.VK_BACK_SPACE && evt.getKeyChar() != KeyEvent.VK_SHIFT) {
                evt.consume();
                getToolkit().beep();
            }
        }
    }//GEN-LAST:event_etNombreModificarKeyTyped

    private void etNotaModificarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etNotaModificarKeyTyped
        char num = evt.getKeyChar();
        if (!Character.isDigit(num) && evt.getKeyChar() != KeyEvent.VK_BACK_SPACE && evt.getKeyChar() != KeyEvent.VK_COMMA) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_etNotaModificarKeyTyped

    private void etFechaModificarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etFechaModificarKeyTyped
        char dig = evt.getKeyChar();
        if (!Character.isDigit(dig) && evt.getKeyChar() != KeyEvent.VK_SLASH && evt.getKeyChar() != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "El formato de la fecha es: dd/mm/yy", "Error en el formato", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_etFechaModificarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModificarDialog dialog = new ModificarDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bModificar;
    private javax.swing.JFormattedTextField etFechaModificar;
    private javax.swing.JTextField etNombreModificar;
    private javax.swing.JFormattedTextField etNotaModificar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
